version: "3.3"

services:
  mlb-backend:
    build: .
    container_name: mlb-backend
    working_dir: /app
    ports:
      - "5000:5000"
    volumes:
      # CSV 파일들을 볼륨으로 마운트
      - ./*.csv:/app/
      # 데이터 파일들을 볼륨으로 마운트 (선택사항 - 폴더가 있을 때만)
      # - ./data:/app/data
      # 로그 파일들을 볼륨으로 마운트 (선택사항 - 폴더가 있을 때만)
      # - ./logs:/app/logs
      # 출력 로그 파일 마운트 (비활성화)
      # - ./output.log:/app/output.log
    environment:
      - FLASK_APP=mlb_dashboard.py
      - FLASK_ENV=production
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/app
    command: sh -c "pwd && ls -la && echo '=== gunicorn 실행 ===' && python -c 'import sys; print(sys.path)' && gunicorn --config gunicorn.conf.py mlb_dashboard:app"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - mlb-network
  nginx:
    image: nginx:alpine
    container_name: mlb-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - mlb-backend
    networks:
      - mlb-network

networks:
  mlb-network:
    driver: bridge
