version: "3.8"

services:
  mlb-backend:
    build: .
    container_name: mlb-backend
    ports:
      - "5000:5000"
    volumes:
      # 데이터 파일들을 볼륨으로 마운트 (선택사항)
      - ./data:/app/data
      # 로그 파일들을 볼륨으로 마운트
      - ./logs:/app/logs
      # 출력 로그 파일 마운트 (비활성화)
      # - ./output.log:/app/output.log
    environment:
      - FLASK_APP=mlb_dashboard.py
      - FLASK_ENV=production
      - PYTHONUNBUFFERED=1
    command: python mlb_dashboard.py > output.log 2>&1
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
