services:
  nginx-proxy:
    image: nginx:alpine
    container_name: central-nginx
    ports:
      - "80:80"
      - "443:443" # HTTPS용 (나중에 SSL 설정 시)
    volumes:
      - ../nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ../nginx/index.html:/usr/share/nginx/html/index.html:ro
      - ../nginx:/usr/share/nginx/html:ro
      - ./ssl:/etc/nginx/ssl:ro # SSL 인증서용 (선택사항)
      - ./logs:/var/log/nginx # 로그 저장용
    networks:
      - mlb-network
    restart: unless-stopped
    depends_on:
      - mlb-backend

  # MLB 백엔드 서비스
  mlb-backend:
    build: ..
    container_name: mlb-backend
    expose:
      - "5000" # 외부 포트 노출 제거, 내부 네트워크에서만 접근
    volumes:
      - ../data:/app/data
      - ../logs:/app/logs
    environment:
      - FLASK_APP=mlb_dashboard.py
      - FLASK_ENV=production
      - PYTHONUNBUFFERED=1
    command: gunicorn --bind 0.0.0.0:5000 --workers 4 --timeout 120 --access-logfile - --error-logfile - mlb_dashboard:app
    restart: unless-stopped
    networks:
      - mlb-network

networks:
  mlb-network:
    driver: bridge
